### ISSUE TITLE
update README with projection information

### ISSUE THREAD

**Issue by mapsam** [mapsam/project-linework#10]
readme files should be updated to indicate the originally-intended projection, since the JSONs don't have that included

**Comment by mapsam** [comment]
@pinakographos I can't really remember how to go about doing this or why it was a big deal - any insight?

**Comment by pinakographos** [comment]
Hmm. Well, it would be good to know for at least some of them. The hexagons
in wargames won't be regular, or the circles in Geo-metro circular, if
they're not in the designed projection. But I thought we put that info in
the readme files already? Maybe not. Could be worth checking first, though.
Right now the downloads aren't working for me.

**Comment by mapsam** [comment]
Currently updating all amazon downloads. Need to rezip everything so it's taking a little bit. Sorry!

**Comment by pinakographos** [comment]
Just grabbed one of the new downloads and, in fact, there is no projection
information. My mistake!

I can add text, but since you have access to the actual downloadable files,
I'll just put here what each should say. Could you add this text on a new
line after the "Public domain" statement in each README?

*Linework set: *add this text after the public domain line.

*Wargames*: A Gall Stereographic projection is necessary for the hexagon
grid to remain regular.
*Twenty Seventy:* A Gall Stereographic projection is necessary for the line
angles to remain at 20 and 70 degrees as intended.
*Times Approximate*: This linework appears to have been originally designed
for a Mercator projection.
*Liana: *Originally designed for use on a Gall Stereographic projection.
*Geo-Metro: *This linework is designed for use on a Lambert Conformal Conic
projection, with standard parallels at 20º and 60º, and a -96º central
meridian.
*Charmingly Inaccurate: *This linework appears to have been originally
designed to fit on an Equidistant Conic projection, with standard parallels
at 33º and 45º, and a -96º central meridian.
*Elmer Casual: *Originally designed for use on a Gall Stereographic
projection.


Also, would it be better if they were Readme.txt, rather than .md?

No one actually reads READMEs, I know, but at least we'll have done our due
diligence in telling people how to make stuff look right.

**Comment by mapsam** [comment]
I changed them to `.md` so they show up better in Github, but can switch it back if you want!

Will get that text in and update asap.

**Comment by pinakographos** [comment]
Is the Github tied to the aws download? I figured since they were separate,
we could rename the download one.

**Comment by mapsam** [comment]
I zip up the github files when we change them, but am happy changing back to `.txt` files in completely - was just a quick idea.

**Comment by pinakographos** [comment]
Might be a little more broadly useful, when considering the final form in
which they're used is on the desktop, rather than GitHub.

Thanks for all your hard work on this! We need to put your name somewhere
on the page credits.
